export const ADD_RESIDENT="ADD_RESIDENT";
export const REMOVE_RESIDENT="REMOVE_RESIDENT";
export const EDIT_RESIDENT="EDIT_RESIDENT";
export const SET_FORM="SET_FORM";
export const SET_CURRENTRESIDENT="SET_CURRENTRESIDENT";